---
apiVersion: v1
kind: Pod
metadata: 
  name: nodejs-pod
  labels:
    app: nodejs-app
spec: 
  serviceAccountName: ecr-account
  containers:
    - image: 211125375984.dkr.ecr.us-east-1.amazonaws.com/nodejs_project:1.0
      ports: 
        - containerPort: 3000
          name: nodejs-port
          protocol: TCP
      name: nodejs-container
  imagePullSecrets:
    - name: ecr-secret
